### ISSUE TITLE
Problem building amd64 image

### ISSUE THREAD

**Issue by beeva-enriqueotero** [SaMnCo/docker-neuraltalk2#1]
I tried to build an image from amd64 Dockerfile and I got the following error:

INFO[0614] The command [/bin/sh -c cd /opt/neural-networks &&     wget https://raw.githubusercontent.com/torch/ezinstall/master/install-deps &&     chmod +x ./install-deps &&     ./install-deps &&     git clone https://github.com/torch/distro.git /opt/neural-networks/torch --recursive &&     cd /opt/neural-networks/torch &&     ./install.sh -b &&     . ~/.bashrc] returned a non-zero code: 137 

Regards :)

**Comment by SaMnCo** [comment]
Fixed, let me know if it now works for you and I'll close it.

**Comment by beeva-enriqueotero** [comment]
It works now. Thanks!
