### ISSUE TITLE
Problem running image from Docker Hub

### ISSUE THREAD

**Issue by beeva-enriqueotero** [SaMnCo/docker-neuraltalk2#2]
I tried to run samnco/neuraltalk2:latest image from Docker Hub with `docker run -it samnco/neuraltalk2:latest` and I got the following error: 

/opt/neural-networks/torch/install/bin/luajit: ...ural-networks/torch/install/share/lua/5.1/torch/File.lua:199: read error: read 0 blocks instead of 1 at /opt/neural-networks/torch/pkg/torch/lib/TH/THDiskFile.c:314
stack traceback:
    [C]: in function 'readInt'
    ...ural-networks/torch/install/share/lua/5.1/torch/File.lua:199: in function 'readObject'
    ...ural-networks/torch/install/share/lua/5.1/torch/File.lua:319: in function 'load'
    eval.lua:73: in main chunk
    [C]: in function 'dofile'
    ...orks/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

By the way my docker version doesn't understand the "-b" flag. And I also can't find it in the reference guide https://docs.docker.com/engine/reference/run/

I'm using Docker version 1.6.1 on Ubuntu 14.04 x86_64

Regards :)

**Comment by SaMnCo** [comment]
Oups, I meant -d (fixed in doc now). 
The image should now work properly. I messed up with the lua code. Let me know if fixed now on your end.

**Comment by beeva-enriqueotero** [comment]
The image is working. Thanks :)

Anyway the performance is much slower than I expected. I will close this issue and open a new one with more info about this new topic.
