### ISSUE TITLE
About performance in CPU mode

### ISSUE THREAD

**Issue by beeva-enriqueotero** [SaMnCo/docker-neuraltalk2#3]
I've run samnco/neuraltalk2:latest in my laptop (Intel QuadCore@2.5Ghz). And performance was very slow :(

Concretely, for a given dataset of pictures, processing time per image was around 50x slower than I expected (100s vs 2s on average).

I am using Docker version 1.6.1 on Ubuntu 14.04 x86_64

**Comment by beeva-enriqueotero** [comment]
Moreover I was surprised that despite flag  <code>-num_images -1</code> in <code>install.sh</code> it processes all the files that I put in folder /data/images

**Comment by SaMnCo** [comment]
@beeva-enriqueotero I think the -1 flag means that the algorithm processes all images before computing the performance evaluation. 

FYI, I have the same feedback when I run on my (old) desktop (Core i7 860 quad core @2.8GHz, 16GB RAM). 

AFAIKS, running a single container, Docker gives away 100% of the performance of the host. If more containers exist,  resources are shared equally. Furthermore, the performance obtained through containers doesn't suffer from overhead as the kernel executes directly. 

Can you explain "what you expected"? What are you comparing here (ie. what takes 100s, what takes 2?)

Also, maybe this would be more interesting to share in the original repo as it's a generic concern and not specifically linked to these images.

**Comment by beeva-enriqueotero** [comment]
You're right about the -num_images flag. I'd better read the comments in eval.lua before :)

Regarding the performance I was comparing to https://github.com/beeva-enriqueotero/docker-neuraltalk2, that runs approximately 50x faster on my laptop, with the same dataset and config.

I would try to update this issue as far as I get more info about it. By the way I suppose it's something specifically related to the image. Though I'm not sure.

**Comment by SaMnCo** [comment]
OK thanks for the update.

One thing you may want to look at: your images are bigger because they
include the model natively. My images download the model at first run
(unless you mount the /data/model volume). That means 1GB download, then
unzip, maybe it can increase the first run time.
However you should not have such a difference on second or third runs. If
so, there is a big issue somewhere!!

On Mon, Dec 14, 2015 at 1:48 PM, Enrique Otero notifications@github.com
wrote:

> You're right about the -num_images flag. I'd better read the comments in
> eval.lua before :)
> 
> Regarding the performance I was comparing to
> https://github.com/beeva-enriqueotero/docker-neuraltalk2, that runs
> approximately 50x faster on my laptop, with the same dataset and config.
> 
> I would try to update this issue as far as I get more info about it. By
> the way I suppose it's something specifically related to the image. Though
> I'm not sure.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SaMnCo/docker-neuraltalk2/issues/3#issuecomment-164428454
> .

## 

SaM'n'Co
R'U Ready? I was BORN ready!

**Comment by beeva-enriqueotero** [comment]
I've just realized what slows down the execution of your image on my computer! It's the installation of Torch addons from https://github.com/mvitez/torch7.git

By skipping this instruction on the Dockerfile, I get the following error:
<code>/opt/neural-networks/torch/install/bin/luajit: eval.lua:74: attempt to call method 'longSize' (a nil value)</code>

Then if a replace SaMnCo/neuraltalk2 repo with original karpathy/neuraltalk2 everything is ok. I guess it's something related with your implementation for loading the model by using torch.DiskFile. But I'm not sure by now.

**Comment by SaMnCo** [comment]
I added this instruction set following the answer given by @soumith in
https://github.com/karpathy/neuraltalk2/issues/32

It updates the load function to add some functionality (like using
longSize), which @soumith thought may clear up the ARM 32b issue I was
having.

I you remove that line, you should also revert eval.lua to the original
file (with torch.load(checkpoint)) to remove the error you are getting.

I am looking into different things right now but may do some benchmarking
during holiday now that you mention it...

On Thu, Dec 17, 2015 at 4:33 PM, Enrique Otero notifications@github.com
wrote:

> I've just realized what slows down the execution of your image on my
> computer! It's the installation of Torch addons from
> https://github.com/mvitez/torch7.git
> 
> By skipping this instruction on the Dockerfile, I get the following error:
> /opt/neural-networks/torch/install/bin/luajit: eval.lua:74: attempt to
> call method 'longSize' (a nil value)
> 
> Then if a replace SaMnCo/neuraltalk2 repo with original
> karpathy/neuraltalk2 everything is ok. Though I don't know why.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SaMnCo/docker-neuraltalk2/issues/3#issuecomment-165485040
> .

## 

SaM'n'Co
R'U Ready? I was BORN ready!

**Comment by SaMnCo** [comment]
Closing thanks to the merge request.
