### ISSUE TITLE
http://localhost:8000/vis not displaying anything

### ISSUE THREAD

**Issue by jss367** [SaMnCo/docker-neuraltalk2#5]
I ran docker run -it -d samnco/neuraltalk2:latest and it downloaded some packages then spit out a large hex number, but I'm not seeing anything in http://localhost:8000/vis. Is there something else I'm supposed to do?

**Comment by SaMnCo** [comment]
Sorry I didn't see that one pop up. I'll have a look. Pretty burried atm, will try sometime next week probably. It's not supposed to operate like you mention, something must have gone horribly wrong somewhere :/

**Comment by trifle** [comment]
@jss367 Did you wait for the model file to download? At start, the container needs to get the ~800MB zip file which will take 20 minutes to one hour. The website is only accessible afterwards.

BTW, you can check what the container is doing by looking at the process tree (for example with htop). Or you can use the hex number (that's the docker image ID) to get the logs. While downloading it will display:

```
$ sudo docker logs 756b4902633f80521106a68809e1de6ffa584951be5f93093a63f047706de54c
--2016-05-17 18:44:41--  http://cs.stanford.edu/people/karpathy/neuraltalk2/checkpoint_v1_cpu.zip
Resolving cs.stanford.edu (cs.stanford.edu)... 171.64.64.64
Connecting to cs.stanford.edu (cs.stanford.edu)|171.64.64.64|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 853865476 (814M) [application/zip]
Saving to: 'checkpoint_v1_cpu.zip'
```

**Comment by jss367** [comment]
@trifle I believe it downloaded everything.
I just got it working without Docker though, so it's a moot point now. Thanks for responding though.

**Comment by tadjik1** [comment]
Hi there. Please reopen this issue, I have the next env:

```
macos

docker -v
Docker version 1.12.0, build 8eab29e

docker-machine -v
docker-machine version 0.8.0, build b85aac1

docker-compose -v
docker-compose version 1.8.0, build f3628c7
```

after starting container I don't see anything in browser:

```
docker run -it -d -p 8000:8000 samnco/neuraltalk2:latest
2fc76e4478088a561d0475860ece703482ac8ef3e9e6601516bca6dc8f783936

docker logs 2fc76e4478088a561d0475860ece703482ac8ef3e9e6601516bca6dc8f783936
--2016-08-19 20:42:43--  http://cs.stanford.edu/people/karpathy/neuraltalk2/checkpoint_v1_cpu.zip
Resolving cs.stanford.edu (cs.stanford.edu)... 171.64.64.64
Connecting to cs.stanford.edu (cs.stanford.edu)|171.64.64.64|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 853865476 (814M) [application/zip]
Saving to: 'checkpoint_v1_cpu.zip'
```

all attempts to open url in browser are unsuccessful:

```
⇒  curl http://localhost:8000/vis
curl: (52) Empty reply from server
```

PS
ups, sorry, but everything work. you should wait about 20 minutes after installing and running container

**Comment by SaMnCo** [comment]
Did you wait long enough to download the 814MB of the checkpoint? This will
run only when the checkpoint is downloaded, which largely depends on your
bandwidth.

Please let it run long enough, test again and let me know if it keeps
failing.

++
Sam
